name: Java CI with Maven

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn clean install -Djava.awt.headless=true  # Adding headless mode here

    - name: Run tests
      run: mvn test -Djava.awt.headless=true  # Ensuring tests run in headless mode
